apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Release.Name }}-simulator-config
  namespace: {{ .Release.Namespace }}

data:
  CDRHOST: {{ .Release.Name }}-receiver-service
  CDRPORT: {{ .Values.simulator.ports.cdr | quote }}

  NATHOST: {{ .Release.Name }}-receiver-service
  NATPORT: {{ .Values.simulator.ports.nat | quote }}

  RECORDCOUNT: {{ .Values.simulator.recordCount | quote }}
  DATATYPE: {{ .Values.simulator.datatype | quote }}
  TIMESTAMP: {{ .Values.simulator.timestamp | quote }}
  TIMEPERIOD: {{ .Values.simulator.timeperiod | quote }}